apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ghcr.io/gerhard/kubehuddle:latest@sha256:f20bde2e472e676d79a9e6ed1ec1566cbe991691af2e71cd814f874986c5dc2e
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 0.1
              memory: 16Mi
            limits:
              cpu: 0.2
              memory: 32Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
              httpHeaders:
                - name: Host
                  value: localhost
            periodSeconds: 10
            timeoutSeconds: 9
          startupProbe:
            httpGet:
              path: /
              port: http
              httpHeaders:
                - name: Host
                  value: localhost
            failureThreshold: 10
            periodSeconds: 10
